package in.bitlogic.digipokket.loan.app.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Enquiry {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer enquiryId;
	private String firstName;
	private String middleName;
	private String lastName;
	private Integer age;
	private Long mobileNo;
	private String panNo;
	private String city;
	private String dateOfBirth;
	private String emailId;
	private Character gender;
	private Integer cibilScore;
	private String cibilStatus;  //-----------autoGenerated
	
}
